### ISSUE TITLE
Publish in Maven Central Repository

### ISSUE THREAD

**Issue by jjszucs** [pmairif/jcprogress#1]
Your library is very useful. In order to better support Maven-built projects, could you please publish your library to the Maven Central Repository?

Here is one article that provides instructions on how to do this: http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/

Thank you for considering this request!

**Comment by pmairif** [comment]
Thanks! I will consider your suggestion.

**Comment by pmairif** [comment]
Finally the thing is out there:
```
<dependency>
  <groupId>com.github.pmairif</groupId>
  <artifactId>jcprogress</artifactId>
  <version>1.0.0</version>
</dependency>

```
😎
